### PR TITLE
Add step-by-step instructions to setup the project locally

### PR DESCRIPTION
**Pull request by paranoicsan**
Contains instructions valid for changes made in https://github.com/learningtapestry/unbounded-lcms/pull/7

### CODE REVIEW

**Review by andersoncardoso — DISMISSED** [review]

**Review by jwrubel — DISMISSED** [review]
Just a couple of changes that I think would help.

**Comment by jwrubel** [comment]
There are two places here were specific passwords are listed. One for the database password and another for the admin user password. The lcms itself uses an [environment variable](https://github.com/learningtapestry/unbounded-lcms/blob/master/config/database.yml#L8) so I think this should match? for the admin user I think it would be good to say something like, "For security reasons we recommend you add a new admin user to the production environment and delete this one once the project is running."

**Comment by paranoicsan** [comment]
@jwrubel I've refactored a wiki a bit. Please take a look.

**Review by jwrubel — APPROVED** [review]
This works for me. Looks good!

**Pull request merged**
